version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth-jwt-otp
    volumes:
      - pg_project:/var/lib/postgresql/auth-jwt-otp
    ports:
      - ${POSTGRES_PORT:-5432}:5432